name = "cf-ws" # todo
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "cf-prem.bmkg.xyz"
custom_domain = true

[vars]
PROXYIP = "35.219.15.90"
UUID = "d2eed70a-4102-42b0-8b40-279e6d901a02"
